# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

defaults: &defaults
  docker:
    - image: gradle:6.6-jdk14
  working_directory: ~/repo

jobs:
  validate-styles:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # Fallbacks to the latest cache
            - v1-dependencies-
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: ./gradlew ktlintCheck
      - run: ./gradlew detekt
  validate-tests:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # Fallbacks to the latest cache
            - v1-dependencies-
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: ./gradlew test
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit \;
          when: always
      - store_test_results:
          path: ./build/test-results/
      - store_artifacts:
          path: ~/test-results/junit
      - store_artifacts:
          path: build/reports/tests/test
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # Fallbacks to the latest cache
            - v1-dependencies-
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: ./gradlew --info clean assemble
      - persist_to_workspace:
          root: ./
          paths:
            - build
  publish-to-repository:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # Fallbacks to the latest cache
            - v1-dependencies-
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: ./gradlew --info publish

workflows:
  version: 2
  build-and-publish:
    jobs:
      - validate-styles
      - validate-tests
      - build:
          requires:
            - validate-styles
            - validate-tests
      - publish-to-repository:
          context: Maven Library
          requires:
            - build
          filters:
            branches:
              only: master
